"""create legacy family table

Revision ID: 2d53885761d1
Revises: 36642820b265
Create Date: 2023-03-20 00:14:47.343902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d53885761d1'
down_revision = '36642820b265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_family',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legacy_name', sa.String(length=50), nullable=False),
    sa.Column('funds', sa.Integer(), nullable=True),
    sa.Column('gender_law', sa.Integer(), nullable=True),
    sa.Column('bloodline_law', sa.Integer(), nullable=True),
    sa.Column('heir_law', sa.Integer(), nullable=True),
    sa.Column('species_law', sa.Integer(), nullable=True),
    sa.Column('exemplar_trait', sa.Integer(), nullable=True),
    sa.Column('type_of_start', sa.String(length=50), nullable=True),
    sa.Column('use_points', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bloodline_law'], ['starting_law.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exemplar_trait'], ['trait.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gender_law'], ['starting_law.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['heir_law'], ['starting_law.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_law'], ['starting_law.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legacy_family')
    # ### end Alembic commands ###
