"""empty message

Revision ID: 4365adcc359d
Revises: b7734080c73d
Create Date: 2023-03-20 22:13:52.147123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4365adcc359d'
down_revision = 'b7734080c73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trait', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=350),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trait', 'description',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
