"""add created_at and updated_at to legacy_family and legacy_family_member tables

Revision ID: b7734080c73d
Revises: 5463dcf74e02
Create Date: 2023-03-20 00:49:21.534737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7734080c73d'
down_revision = '5463dcf74e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legacy_family', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('legacy_family', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('legacy_family_member', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('legacy_family_member', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legacy_family_member', 'updated_at')
    op.drop_column('legacy_family_member', 'created_at')
    op.drop_column('legacy_family', 'updated_at')
    op.drop_column('legacy_family', 'created_at')
    # ### end Alembic commands ###
